### ISSUE TITLE
 Captain Toad: Treasure Tracker StageData BYMLs converted to XML and back don't work

### ISSUE THREAD

**Issue by mariomadproductions** [exelix11/TheFourthDimension#11]
You probably aren't interested in fixing this because it is for another game, but...

I didn't change anything in the XML - and I confirmed that the archive packing worked. I tested using Cemu and used Uwizard for the archive packing.

**Comment by exelix11** [comment]
Unluckily looks like that the byml format used on SM3DW and Treasure Tracker is a different version than the one used on 3ds, iirc there is another tool that can edit mario kart 8 bymls, you should try that.

**Comment by mariomadproductions** [comment]
Okay. I assume [this](https://github.com/TheKoopaKingdom/MK8-Editor) is the tool? I'll try it out.

**Comment by mariomadproductions** [comment]
I haven't got the MK8-editor tool to work, but using your tool on one SM3DW BYML worked perfectly. :P
