### ISSUE TITLE
[Suggestion] Batch tool for converting BYMLs and XMLs and back

### ISSUE THREAD

**Issue by mariomadproductions** [exelix11/TheFourthDimension#12]
Its quite slow having to do a large amount manually.

**Comment by exelix11** [comment]
Done, download version 0.9.1 from the [releases page](https://github.com/exelix11/TheFourthDimension/releases)

**Comment by mariomadproductions** [comment]
This seems to have broken the Japanese text support. Also, could you add a "convert a whole folder" function (or is there an easy way to do that with a batch file)?

**Comment by exelix11** [comment]
Fixed, this also affected saving a level in xml format.

For batch processing an entire folder you can make a bat file like this:
```
for /r %%v in (*.byml) do "C:\Path to\The4Dimension.exe" batch "%%v"
pause
```
pause is important so you can check the log

**Comment by mariomadproductions** [comment]
that doesnt
