### ISSUE TITLE
Windows Defender false positive on release.zip

### ISSUE THREAD

**Issue by mariomadproductions** [exelix11/TheFourthDimension#13]
for Version 0.9.1 and Version 0.9 at least. Any idea why it might have this?

**Comment by exelix11** [comment]
It's not saying it's a virus, it's warning you that the executable doesn't have a verified author and that they don't have any records about it, looks like that when many people use the program this doesn't happen anymore, so for new version the first people to download it will always get that message, the only way to remove it would be to sign it with a digital certificate,but that's not free ¯\\_(ツ)_/¯
Anyway if you are worried about it, it's open source so you can check the code for yourself.

**Comment by mariomadproductions** [comment]
That would explain why it didn't appear in Defender's log (I should have mentioned that was the case). I managed to get it past the check by downloading with Firefox, but there is probably an option to disable the check within Defender. I scanned it after it download - no virus, and I trust that you wouldn't put one in ;P
