### ISSUE TITLE
"Virus Detected"

### ISSUE THREAD

**Issue by NightScript370** [exelix11/TheFourthDimension#16]
Both Opera and Windows 10 identify this as a virus. I think you might want to fix that

**Comment by exelix11** [comment]
I have no control over this, it's a warning that says the program is not in their whitelist, real antivirus programs won't detect it as a virus.
The only way to fix it would be buying a digital certificate and signing the exe, but it's not free ¯\_(ツ)_/¯.
Anyway it's open source, if you don't trust the exe you can check the code and compile it yourself

**Comment by MoonlightCapital** [comment]
opera is for commies

**Comment by NightScript370** [comment]
Hmm... Is there any tutorial on how to compile it? I can't find any in the readme

**Comment by exelix11** [comment]
You should have visual studio and its .net framework and wpf components installed.
Download the repo and open the .sln file, to be safe do a nuget restore, set the build target to Release and click run.
If you're not pratical with visual studio avoid this, this is a scan of the latest release https://www.virustotal.com/it/file/3ff5f5775848a33de127523d2455e08d2685b40a0c2f748333644b04275cd392/analysis/
