### ISSUE TITLE
Toad Treasure Tracker Compatibility

### ISSUE THREAD

**Issue by cualquiercosa327** [exelix11/TheFourthDimension#19]
Hello,i have using some tools from this great editor and it works perfect with Captain Toad (Wii U , 3DS and Switch versions).
But i am unable to load a full level.
Could be some extra option to choose "Captain Toad" and load its levels?
it could be great for adding extra levels and also for could port Mario Odissey levels to Wii U and Mario World levels to 3DS and Switch versions.
Thanks for alls

**Comment by cualquiercosa327** [comment]
I saw you already are doing it as EditorCore pluggin.Thanks you for your great work
Ah,would you port TheFourthDimensions also as a EditorCore pluggin?

**Comment by exelix11** [comment]
I'm not converting T4D to a plug in, at least in the near future, mostly because my focus right now is on odyssey and the 3D Land modding scene is pretty much dead
